---
repo_url: https://yaoyao5296.github.io/chatroom-fdroid/repo
repo_name: ChatRoom
repo_description: ChatRoom App Repository
archive_url: https://yaoyao5296.github.io/chatroom-fdroid/archive
archive_older: 3
repo_keyalias: all-in-one-63-wfbdd
keydname: CN=all-in-one-63-wfbdd, OU=F-Droid
keystorepass: OoQ86/aJ7NdnAbe4bboovuJ0rK07RkcHXoqc+kPf6oE=
keypass: OoQ86/aJ7NdnAbe4bboovuJ0rK07RkcHXoqc+kPf6oE=
